In [1]:
#importing our library
import pandas as pd
import numpy as np

# Question 1
 What's the version of NumPy that you installed?

In [2]:
np.__version__

'1.22.2'

In [3]:
data=pd.read_csv("cars.csv",sep=",")
newdf=pd.read_csv("cars.csv",sep=",")

# Question 2
How many records are in the dataset?

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

# Question  3 


In [5]:
data["Make"].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [6]:
# Chevrolet, Ford, Volkswagen
#solved

# Question 4
What's the number of unique Audi car models in the dataset?

In [7]:
uniq=data[data.Make=="Audi"]["Model"].nunique()

In [8]:
uniq


34

# Question 5
 How many columns in the dataset have missing values?


In [9]:
newdf.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [10]:
#:missing values column 
#1:Engine HP           
#2:Engine Cylinders    
#3:Number of Doors
#4Market Category
#5Engine Fuel Type
 

# Question 6
Find the median value of "Engine Cylinders" column in the dataset.
Next, calculate the most frequent value of the same "Engine Cylinders".
Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
Now, calculate the median value of "Engine Cylinders" once again.

In [11]:

#Find the median value of "Engine Cylinders" column in the dataset.
newdf["Engine Cylinders"].median()

6.0

In [12]:
#Next, calculate the most frequent value of the same "Engine Cylinders".

newdf["Engine Cylinders"].value_counts()


4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [13]:
#Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

newdf["Engine Cylinders"].fillna(4.0).median() #Now, calculate the median value of "Engine Cylinders" once again.

6.0

In [14]:
# solved but no change in the value i tried "mode" also but no change and in mean there was minar changes after "5. ..."

# Question 7
Select all the "Lotus" cars from the dataset.
Select only columns "Engine HP", "Engine Cylinders".
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the first element of w?

In [15]:
rc=data[data.Make=="Lotus"][["Engine HP", "Engine Cylinders"]]

In [16]:
newrc=rc.drop_duplicates()
newrc

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [17]:
x= newrc.values
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [18]:
trans=x.T
trans

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [19]:
xtx=trans.dot(x)
xtx

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [20]:
inv_xtx=np.linalg.inv(xtx)
inv_xtx

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [21]:
inv_xtx.sum()

0.1547573584345781

In [22]:
y=[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [23]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w=inv_xtx.dot(trans).dot(y)
w

array([  4.59494481, -63.56432501])